apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnettest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnettest
  template:
    metadata:
      labels:
        app: dotnettest
    spec:
      containers:
      - name: dotnettest
        image: 'arunbpt7/dotnetcore:latest'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnettest-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dotnettest

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dotnettest-ingress
spec:
  rules:
  - host: dotnettest.apps.ux.hra.nycnet
    http:
      paths:
      - path: /
        backend:
          serviceName: dotnettest-svc
          servicePort: 80
